app = "nos-tlplot"
primary_region = "bom"

[build]
  builder = "paketobuildpacks/builder:base"  # ensures Python buildpack runs
  [build.env]
    BP_PYTHON_VERSION = "3.11.*"             # force Python 3.11 for compatibility with your packages

[processes]
  app = "python app.py"

[http_service]
  internal_port = 8501
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[vm]]
  memory = "512mb"
  cpu_kind = "shared"
  cpus = 1
